//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchBook.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRecursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRecursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatchBook.Recursos.StringRecursos", typeof(StringRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string botonbuscar {
            get {
                return ResourceManager.GetString("botonbuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi biblioteca.
        /// </summary>
        internal static string btnBiblioteca {
            get {
                return ResourceManager.GetString("btnBiblioteca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string btnBuscar {
            get {
                return ResourceManager.GetString("btnBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        internal static string btnCerrarSesion {
            get {
                return ResourceManager.GetString("btnCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string btnEditar {
            get {
                return ResourceManager.GetString("btnEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        internal static string btnEntrar {
            get {
                return ResourceManager.GetString("btnEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foro.
        /// </summary>
        internal static string btnForo {
            get {
                return ResourceManager.GetString("btnForo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string btnInformacion {
            get {
                return ResourceManager.GetString("btnInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        internal static string btnPerfil {
            get {
                return ResourceManager.GetString("btnPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal.
        /// </summary>
        internal static string btnPrincipal {
            get {
                return ResourceManager.GetString("btnPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        internal static string btnregistro {
            get {
                return ResourceManager.GetString("btnregistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string btnSalir {
            get {
                return ResourceManager.GetString("btnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir.
        /// </summary>
        internal static string btnSubir {
            get {
                return ResourceManager.GetString("btnSubir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir página.
        /// </summary>
        internal static string btnSubirPagina {
            get {
                return ResourceManager.GetString("btnSubirPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir Reseña.
        /// </summary>
        internal static string btnSubirReseña {
            get {
                return ResourceManager.GetString("btnSubirReseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amor a primera página.
        /// </summary>
        internal static string lblAMor {
            get {
                return ResourceManager.GetString("lblAMor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor.
        /// </summary>
        internal static string lblAutor {
            get {
                return ResourceManager.GetString("lblAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BUSCAR LIBRO.
        /// </summary>
        internal static string lblBuscarLibro {
            get {
                return ResourceManager.GetString("lblBuscarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Con..
        /// </summary>
        internal static string lblConfirmarCon {
            get {
                return ResourceManager.GetString("lblConfirmarCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenido a mostrar.
        /// </summary>
        internal static string lblContenido {
            get {
                return ResourceManager.GetString("lblContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña: .
        /// </summary>
        internal static string lblContraseña {
            get {
                return ResourceManager.GetString("lblContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string lblDirección {
            get {
                return ResourceManager.GetString("lblDirección", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo:.
        /// </summary>
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Nacimiento: .
        /// </summary>
        internal static string lblFechaNacimiento {
            get {
                return ResourceManager.GetString("lblFechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FORO.
        /// </summary>
        internal static string lblForo {
            get {
                return ResourceManager.GetString("lblForo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MI BIBLIOTECA.
        /// </summary>
        internal static string lblMiBiblioteca {
            get {
                return ResourceManager.GetString("lblMiBiblioteca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar Contraseña.
        /// </summary>
        internal static string lblMostrarContrasenya {
            get {
                return ResourceManager.GetString("lblMostrarContrasenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página.
        /// </summary>
        internal static string lblPagina {
            get {
                return ResourceManager.GetString("lblPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PERFIL.
        /// </summary>
        internal static string lblPerfil {
            get {
                return ResourceManager.GetString("lblPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?¡Regístrate ahora!.
        /// </summary>
        internal static string lblRegistro {
            get {
                return ResourceManager.GetString("lblRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reseña: .
        /// </summary>
        internal static string lblReseña {
            get {
                return ResourceManager.GetString("lblReseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SUBIR LIBRO.
        /// </summary>
        internal static string lblSubirLibro {
            get {
                return ResourceManager.GetString("lblSubirLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título:.
        /// </summary>
        internal static string lblTitulo {
            get {
                return ResourceManager.GetString("lblTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string lblUsuario {
            get {
                return ResourceManager.GetString("lblUsuario", resourceCulture);
            }
        }
    }
}
